image: microsoft/dotnet:latest

stages:
  - build
  - test


before_script:
  - "dotnet restore"

build SDK.Core:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.Core"
  script:
    - "cd $build_path"
    - "dotnet build"

build SDK.DAL.Interfaces:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.DAL.Interfaces"
  script:
    - "cd $build_path"
    - "dotnet build"
    
build SDK.Enums:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.Enums"
  script:
    - "cd $build_path"
    - "dotnet build"

build SDK.GameObjects:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.GameObjects"
  script:
    - "cd $build_path"
    - "dotnet build"

build SDK.Packets:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.Packets"
  script:
    - "cd $build_path"
    - "dotnet build"

build SDK.Packets:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.Systems"
  script:
    - "cd $build_path"
    - "dotnet build"


build SDK.DTO:
  stage: build
  variables:
    build_path: "src/NosSharp.SDK.DTO"
  script:
    - "cd $build_path"
    - "dotnet build"

test SDK.Core:
  stage: test
  variables:
    build_path: "test/NosSharp.SDK.Core.Test"
  script:
    - "cd $build_path"
    - "dotnet test"